# Generated by Django 5.2.7 on 2025-11-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blog_image_alter_comment_post_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, default='\x07pp\\static\x07pp\\content\temp.jpg', null=True, upload_to='', verbose_name='Путь к картинке'),
        ),
    ]
