# Generated by Django 5.2.7 on 2025-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, default='app/content/banner.jpg', null=True, upload_to='', verbose_name='Путь к картинке'),
        ),
    ]
