# Generated by Django 5.2.7 on 2025-11-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='app/content/banner.jpg', upload_to='', verbose_name='Путь к картинке'),
        ),
    ]
